# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'createaccount.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formm(object):
    def setuppUi(self, Form):
        Form.setObjectName("yeni")
        Form.resize(1100, 803)
        Form.setAcceptDrops(True)
        Form.setStyleSheet("background:rgb(50, 156, 146);")
        self.baslik = QtWidgets.QLabel(Form)
        self.baslik.setGeometry(QtCore.QRect(200, 80, 651, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(22)
        font.setBold(False)
        font.setWeight(50)
        self.baslik.setFont(font)
        self.baslik.setStyleSheet("")
        self.baslik.setObjectName("baslik")
        self.kullaniciadi = QtWidgets.QLineEdit(Form)
        self.kullaniciadi.setGeometry(QtCore.QRect(400, 230, 321, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.kullaniciadi.setFont(font)
        self.kullaniciadi.setMouseTracking(True)
        self.kullaniciadi.setTabletTracking(True)
        self.kullaniciadi.setAcceptDrops(False)
        self.kullaniciadi.setStyleSheet("background:rgb(70, 15, 87);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;\n"
"")
        self.kullaniciadi.setInputMethodHints(QtCore.Qt.ImhNone)
        self.kullaniciadi.setInputMask("")
        self.kullaniciadi.setText("")
        self.kullaniciadi.setReadOnly(False)
        self.kullaniciadi.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.kullaniciadi.setClearButtonEnabled(False)
        self.kullaniciadi.setObjectName("kullaniciadi")
        self.sifrekutusu = QtWidgets.QLineEdit(Form)
        self.sifrekutusu.setGeometry(QtCore.QRect(400, 340, 321, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sifrekutusu.setFont(font)
        self.sifrekutusu.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.sifrekutusu.setMouseTracking(False)
        self.sifrekutusu.setStyleSheet("background:rgb(70, 15, 87);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.sifrekutusu.setText("")
        self.sifrekutusu.setObjectName("sifrekutusu")
        self.kullanicikekle = QtWidgets.QPushButton(Form)
        self.kullanicikekle.setGeometry(QtCore.QRect(450, 550, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.kullanicikekle.setFont(font)
        self.kullanicikekle.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.kullanicikekle.setObjectName("kullanicikekle")
        self.sifrekutusu_2 = QtWidgets.QLineEdit(Form)
        self.sifrekutusu_2.setGeometry(QtCore.QRect(400, 440, 321, 91))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.sifrekutusu_2.setFont(font)
        self.sifrekutusu_2.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.sifrekutusu_2.setMouseTracking(False)
        self.sifrekutusu_2.setStyleSheet("background:rgb(70, 15, 87);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.sifrekutusu_2.setText("")
        self.sifrekutusu_2.setObjectName("sifrekutusu_2")
        self.kullanicikekle_2 = QtWidgets.QPushButton(Form)
        self.kullanicikekle_2.setGeometry(QtCore.QRect(450, 630, 241, 71))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.kullanicikekle_2.setFont(font)
        self.kullanicikekle_2.setStyleSheet("background:rgb(150, 27, 70);\n"
"border:none;\n"
"border-radius:30px;\n"
"color:white;")
        self.kullanicikekle_2.setObjectName("kullanicikekle_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.baslik.setText(_translate("Form", " KULANICI OLUŞTURMA EKRANI"))
        self.kullaniciadi.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-weight:400; font-style:italic; color:#aa0000;\">Kullanıcı Adınız Sadece Harflerden Oluşabilir.</span></p></body></html>"))
        self.kullaniciadi.setPlaceholderText(_translate("Form", "      Kullanıcı Adını Giriniz"))
        self.sifrekutusu.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic; color:#aa0000;\">Şifreniz Sadece Sayılardan Oluşabilir.</span></p></body></html>"))
        self.sifrekutusu.setPlaceholderText(_translate("Form", "      Lütfen Şifrenizi Giriniz"))
        self.kullanicikekle.setText(_translate("Form", "KULLANICI EKLE"))
        self.sifrekutusu_2.setToolTip(_translate("Form", "<html><head/><body><p align=\"center\"><span style=\" font-style:italic; color:#aa0000;\">Şifreniz Sadece Sayılardan Oluşabilir.</span></p></body></html>"))
        self.sifrekutusu_2.setPlaceholderText(_translate("Form", " Lütfen Şifrenizi Tekrar Giriniz"))
        self.kullanicikekle_2.setText(_translate("Form", "GİRİŞ YAPINIZ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Formm()
    ui.setuppUi(Form)
    Form.show()
    sys.exit(app.exec_())
