# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Formmm(object):
    def setupUi(self, Formmm):
        Formmm.setObjectName("Formmm")
        Formmm.resize(1053, 643)
        self.widget1 = MatplotlibWidget(Formmm)
        self.widget1.setGeometry(QtCore.QRect(390, 10, 501, 281))
        self.widget1.setStyleSheet("background-color: rgb(229, 255, 254);")
        self.widget1.setObjectName("widget1")
        self.widget_2 = MatplotlibWidget(Formmm)
        self.widget_2.setGeometry(QtCore.QRect(400, 310, 491, 271))
        self.widget_2.setStyleSheet("background-color: rgb(172, 242, 255);")
        self.widget_2.setObjectName("widget_2")
        self.pushButton23 = QtWidgets.QPushButton(Formmm)
        self.pushButton23.setGeometry(QtCore.QRect(50, 170, 181, 61))
        self.pushButton23.setObjectName("pushButton23")

        self.retranslateUi(Formmm)
        QtCore.QMetaObject.connectSlotsByName(Formmm)

    def retranslateUi(self, Formmm):
        _translate = QtCore.QCoreApplication.translate
        Formmm.setWindowTitle(_translate("Formmm", "Form"))
        self.pushButton23.setText(_translate("Formmm", "PushButton"))
from matplotlibwidget import MatplotlibWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Formmm = QtWidgets.QWidget()
    ui = Ui_Formmm()
    ui.setupUi(Formmm)
    Formmm.show()
    sys.exit(app.exec_())
